extends "res://tests/guild_smoke.gd"
## Uses an isolated config. Run with a renderer to exercise native window changes.

func run_checks() -> void:
	var video = root.get_node("DisplaySettings")
	video.config_path = "user://display_test_%d.cfg" % OS.get_process_id()
	var config_file: String = ProjectSettings.globalize_path(video.config_path)
	var main = load("res://scenes/main_menu.tscn").instantiate()
	root.add_child(main)
	current_scene = main
	await frames()
	check(root.content_scale_size == Vector2i(640, 360), "16:9 logical canvas")
	check(root.content_scale_mode == Window.CONTENT_SCALE_MODE_CANVAS_ITEMS, "UI renders at output resolution")
	check(root.content_scale_stretch == Window.CONTENT_SCALE_STRETCH_INTEGER, "Integer scaling keeps pixel edges even")
	video.load_preferences()
	check(not video.fullscreen and video.resolution in video.RESOLUTIONS, "Missing config loads safe defaults")
	video.open_menu()
	await frames()
	check(paused and video.menu.is_open, "Display menu pauses its caller")
	check(Rect2(0, 0, 640, 360).encloses(video.menu.panel.get_global_rect()), "Settings fit 16:9")
	await capture("display-settings.png")
	check(not video.begin_preview(Vector2i(1000, 1000), false), "Unsupported aspect is rejected")
	var original_size := root.size
	var original_mode := root.mode
	video.menu.resolution_choice.select(0)
	video.menu.mode_choice.select(0)
	video.menu.preview()
	await frames()
	check(video.previewing and not FileAccess.file_exists(video.config_path), "Preview never writes settings")
	if DisplayServer.get_name() != "headless": check(root.size == Vector2i(640, 360), "Window changes to selected resolution")
	await capture("display-confirmation.png")
	await key_press(KEY_ESCAPE)
	await frames()
	check(not video.previewing and video.menu.is_open and paused, "Escape reverts preview without closing settings")
	if DisplayServer.get_name() != "headless": check(root.size == original_size and root.mode == original_mode, "Rollback restores actual window")
	video.menu.resolution_choice.select(0)
	video.menu.preview()
	video.menu.seconds_left = 0.01
	await frames(5)
	check(not video.previewing and not FileAccess.file_exists(video.config_path), "Timeout restores settings even while paused")
	video.menu.resolution_choice.select(0)
	video.menu.preview()
	video.menu.confirm()
	check(not video.previewing and FileAccess.file_exists(video.config_path), "Only confirmed settings reach disk")
	video.resolution = Vector2i(1280, 720)
	video.load_preferences()
	check(video.resolution == Vector2i(640, 360), "Confirmed size survives reload")
	for size in video.RESOLUTIONS:
		if not video.fits_window(size):
			check(not video.begin_preview(size, false), "Oversized window cannot hide controls")
			continue
		check(video.begin_preview(size, false), "Supported window size applies: " + str(size))
		await frames()
		if DisplayServer.get_name() != "headless":
			check(root.size == size, "Native window size matches choice")
			await RenderingServer.frame_post_draw
			check(root.get_texture().get_image().get_size() == size, "Frame is rendered at selected output resolution")
		video.cancel_preview()
		await frames()
	video.menu.mode_choice.select(1)
	video.menu.update_note()
	check(video.menu.resolution_choice.disabled, "Fullscreen explicitly uses monitor resolution")
	video.menu.preview()
	await frames(6)
	if DisplayServer.get_name() != "headless": check(root.mode == Window.MODE_EXCLUSIVE_FULLSCREEN, "Native fullscreen works")
	await capture("display-fullscreen.png")
	video.menu.revert()
	await frames()
	await key_press(KEY_ESCAPE)
	check(not video.menu.is_open and not paused, "Closing settings restores main menu")
	main.queue_free()
	await frames()
	var game = load("res://scenes/guild.tscn").instantiate()
	root.add_child(game)
	current_scene = game
	await frames()
	game.pause_menu.open_pause()
	video.open_menu()
	await key_press(KEY_ESCAPE)
	check(not video.menu.is_open and paused and game.pause_menu.is_open, "Closing video settings preserves game pause")
	game.pause_menu.close_pause()
	DirAccess.remove_absolute(config_file)
	print("DISPLAY OPTIONS: %d failure(s)" % failures)
	quit(0 if failures == 0 else 1)
