extends "res://tests/save_and_pause.gd"

func walk_to(target: Vector2, limit: int = 450) -> void:
	for frame in range(limit):
		var difference: Vector2 = target - game.player.position
		if difference.length() < 4: break
		for entry in [["move_left", difference.x < -2], ["move_right", difference.x > 2], ["move_up", difference.y < -2], ["move_down", difference.y > 2]]:
			if entry[1]: Input.action_press(entry[0])
			else: Input.action_release(entry[0])
		await frames(1)
	for action in ["move_left", "move_right", "move_up", "move_down"]: Input.action_release(action)
	await frames(2)
	check(game.player.position.distance_to(target) < 5, "Walkable route to " + str(target))

func inspect_here() -> void:
	await key_press(KEY_E)
	check(game.inspection.is_open and not game.player.controls_enabled, "Inspection blocks movement")
	await frames()
	check(Rect2(0, 0, 640, 360).encloses(game.inspection.panel.get_global_rect()), "Inspection fits 16:9")

func run_checks() -> void:
	state = root.get_node("GameState")
	state.save_directory = "user://exploration_test_%d" % OS.get_process_id()
	clear_test_saves()
	state.reset_game()
	state.active_slot = 1
	state.game_active = true
	game = await load_world(state.SQUARE_SCENE)
	game.player.position = Vector2(714, 398)
	await frames()
	await capture("exploration-exit.png")
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	check(game.scene_file_path == state.OUTSKIRTS_SCENE and state.quest_stage == state.QuestStage.AVAILABLE, "Road accessible without accepting any quest")
	check(state.read_slot(1).location_scene == state.OUTSKIRTS_SCENE, "Arrival autosaves new location")
	await capture("exploration-road.png")
	check(not state.discover("road_cache"), "Cannot claim discovery remotely")
	await walk_to(Vector2(160, 370))
	await walk_to(Vector2(560, 370))
	await walk_to(Vector2(560, 304))
	check(not state.discover("shortcut"), "Gate cannot open from locked side")
	Input.action_press("move_up")
	await frames(30)
	Input.action_release("move_up")
	check(game.player.position.y >= 288, "Closed gate physically blocks the shortcut")
	await inspect_here()
	check(not game.inspection.action.visible, "Locked side offers no unlock button")
	game.inspection.close()
	await walk_to(Vector2(160, 330))
	await walk_to(Vector2(160, 190))
	await walk_to(Vector2(160, 116))
	await walk_to(Vector2(88, 116))
	await capture("exploration-cache.png")
	await inspect_here()
	check(not state.inventory.has("watch_notes"), "Inspecting a find does not take it")
	await key_press(KEY_ESCAPE)
	check(paused and game.inspection.is_open, "Pause preserves inspection")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_TAB)
	check(game.inspection.action.has_focus(), "Take action is keyboard accessible")
	await key_press(KEY_ENTER)
	check(state.inventory.get("watch_notes", 0) == 1 and "road_cache" in state.discoveries, "Taking notes records item and discovery together")
	check(not state.discover("road_cache"), "Discovery cannot pay twice")
	await key_press(KEY_I)
	await capture("exploration-notes.png")
	check(game.character_panel.info.text.contains("тремя лучами"), "Find has readable inventory description")
	await key_press(KEY_I)
	await walk_to(Vector2(160, 116))
	await walk_to(Vector2(160, 190))
	await walk_to(Vector2(560, 190))
	await capture("exploration-post-exterior.png")
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	check(game.scene_file_path == state.OUTPOST_SCENE, "Post interior loads")
	await walk_to(Vector2(384, 216))
	await walk_to(Vector2(244, 216))
	await walk_to(Vector2(244, 190))
	await inspect_here()
	game.inspection.action.pressed.emit()
	await walk_to(Vector2(384, 216))
	await walk_to(Vector2(600, 216))
	await walk_to(Vector2(600, 160))
	await capture("exploration-post.png")
	await inspect_here()
	await capture("exploration-seal.png")
	game.inspection.action.pressed.emit()
	check(state.save_game(1), "Interior and discoveries can be saved")
	var saved: Dictionary = state.read_slot(1)
	state.reset_game()
	check(state.apply_data(saved), "New exploration save reloads")
	game = await load_world(saved.location_scene)
	check(game.player.position.distance_to(Vector2(600, 160)) < 5 and "sealed_arch" in state.discoveries, "Position and inspected seal survive loading")
	await walk_to(Vector2(600, 216))
	await walk_to(Vector2(384, 216))
	await walk_to(Vector2(384, 428))
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	await walk_to(Vector2(560, 238))
	await inspect_here()
	game.inspection.action.pressed.emit()
	await frames()
	check("shortcut" in state.discoveries and game.gate.get_child(0).disabled, "Opening latch removes gate collision")
	check(state.save_game(1), "Open shortcut saved")
	saved = state.read_slot(1)
	state.reset_game()
	state.apply_data(saved)
	game = await load_world(saved.location_scene)
	check(game.gate.get_child(0).disabled and state.inventory.get("watch_notes", 0) == 1, "Open passage and unique item survive reload")
	await capture("exploration-shortcut.png")
	await walk_to(Vector2(560, 340))
	await walk_to(Vector2(560, 370))
	await walk_to(Vector2(100, 410))
	await walk_to(Vector2(100, 436))
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	check(game.scene_file_path == state.SQUARE_SCENE, "Shortcut leads back to existing square")
	check(state.quest_stage == state.QuestStage.AVAILABLE and state.personal_coins == 0, "Exploration does not invent quest progress or money")
	var legacy: Dictionary = saved.duplicate(true)
	legacy.version = 2
	legacy.location_scene = state.GUILD_SCENE
	legacy.erase("discoveries")
	legacy.inventory = {"delivery_receipt": 1}
	legacy.personal_coins = 37
	legacy.attributes["Сила"] = 4
	check(state.apply_data(legacy) and state.discoveries.is_empty() and state.personal_coins == 37 and state.attributes["Сила"] == 4 and state.inventory.has("delivery_receipt"), "Version 2 migration preserves previous progress")
	legacy.version = 1
	check(state.apply_data(legacy) and state.discoveries.is_empty(), "Version 1 migration supported")
	var invalid: Dictionary = saved.duplicate(true)
	invalid.discoveries = ["not_a_real_discovery"]
	check(not state.apply_data(invalid) and state.personal_coins == 37, "Invalid discovery data rejected before state changes")
	clear_test_saves()
	print("EXPLORATION: %d failure(s)" % failures)
	quit(0 if failures == 0 else 1)
