extends "res://tests/guild_smoke.gd"
## Exercise real UI actions, walking, and scene changes; no disk saves.

var quest_events: int = 0


func run_checks() -> void:
	var state = root.get_node("GameState")
	state.quest_changed.connect(func(): quest_events += 1)
	var game = load("res://scenes/guild.tscn").instantiate()
	root.add_child(game)
	current_scene = game
	await frames(5)
	await key_press(KEY_J)
	check(game.dialogue.mode == "journal" and game.dialogue.is_open, "J opens journal")
	check(game.dialogue.title_label.text == "Пока нет заданий", "Fresh journal is empty")
	check(not game.player.controls_enabled, "Journal blocks walking")
	await capture("journal-empty.png")
	await key_press(KEY_J)
	check(not game.dialogue.is_open and game.player.controls_enabled, "J closes journal without reopening")
	# The square is accessible before accepting; Corvin cannot skip registration.
	game.player.position = Vector2(384, 428)
	await frames()
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	check(game.npc_mode == "corvin", "Guild exit leads to square")
	check(not game.near_portal, "Arrival is outside return trigger")
	await capture("square-arrival.png")
	# Walk the route from the guild to Corvin, verifying it is unobstructed.
	Input.action_press("move_right")
	await frames(200)
	Input.action_release("move_right")
	await frames()
	check(game.near_npc, "Can walk from entrance to Corvin")
	await key_press(KEY_E)
	check(game.dialogue.is_open and state.quest_stage == state.QuestStage.AVAILABLE, "Early Corvin visit does not accept quest")
	await key_press(KEY_ESCAPE)
	game.player.position = Vector2(168, 232)
	await frames()
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	check(game.npc_mode == "mira", "Square entrance returns to guild")
	check(not game.near_portal, "Guild arrival does not retrigger exit")
	game.player.position = Vector2(384, 205)
	await frames()
	await key_press(KEY_E)
	check(game.dialogue.accept_button.visible, "Mira offers acceptance")
	await capture("quest-offer.png")
	game.dialogue.close_button.pressed.emit()
	await frames()
	check(state.quest_stage == state.QuestStage.AVAILABLE, "Declining leaves quest available")
	await key_press(KEY_E)
	await key_press(KEY_TAB)
	check(game.dialogue.accept_button.has_focus(), "Tab selects Accept without accepting")
	await key_press(KEY_ENTER)
	await frames()
	check(state.quest_stage == state.QuestStage.ACCEPTED, "Accept button records quest")
	check(not game.dialogue.accept_button.visible, "Accepted quest cannot be accepted twice")
	check(game.objective_label.text.contains("Корвина"), "HUD points to Corvin")
	game.dialogue.accept_button.pressed.emit()
	check(quest_events == 1, "Acceptance emits one state change")
	await capture("quest-accepted.png")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_J)
	check(game.dialogue.status_label.text.contains("Активных заданий: 1"), "Journal contains one active quest")
	await capture("journal-active.png")
	game.player.position = Vector2(384, 428)
	await frames()
	await key_press(KEY_E)
	check(current_scene == game, "Open journal prevents travel")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	check(state.quest_stage == state.QuestStage.ACCEPTED, "Quest survives travel to square")
	game.player.position = Vector2(526, 281)
	await frames()
	await key_press(KEY_E)
	check(state.quest_stage == state.QuestStage.MET_CORVIN, "Talking to Corvin records meeting")
	check(quest_events == 2, "Meeting emits one state change")
	check(game.dialogue.status_label.text.contains("Награда ещё не получена"), "Meeting does not award reward")
	await capture("corvin-dialogue.png")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_E)
	check(quest_events == 2, "Repeated Corvin dialogue does not duplicate progress")
	await key_press(KEY_ESCAPE)
	game.player.position = Vector2(168, 232)
	await frames()
	await key_press(KEY_E)
	await frames(5)
	game = current_scene
	check(state.quest_stage == state.QuestStage.MET_CORVIN, "Meeting survives return to guild")
	game.player.position = Vector2(384, 205)
	await frames()
	await key_press(KEY_E)
	check(not game.dialogue.accept_button.visible, "Mira retains accepted status after return")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_J)
	check(game.dialogue.status_label.text.contains("Подготовить площадь: 0 / 3"), "Journal reflects assigned work on both maps")
	await capture("journal-corvin.png")
	await key_press(KEY_ESCAPE)
	check(game.player.controls_enabled, "All windows restore movement")
	print("RESULT: %d failure(s)" % failures)
	quit(0 if failures == 0 else 1)
