extends "res://tests/guild_smoke.gd"
## Full solo quest: real inputs, cancellable work, acceptance and one reward.

var state: Node
var game: Node


func interact_at(at: Vector2) -> void:
	game.player.position = at
	await frames()
	await key_press(KEY_E)


func travel_at(at: Vector2) -> void:
	await interact_at(at)
	await frames(5)
	game = current_scene


func press_primary() -> void:
	await key_press(KEY_TAB)
	check(game.dialogue.accept_button.has_focus(), "Primary action is keyboard accessible")
	await key_press(KEY_ENTER)


func run_checks() -> void:
	state = root.get_node("GameState")
	game = load("res://scenes/guild.tscn").instantiate()
	root.add_child(game)
	current_scene = game
	await frames(5)
	check(state.personal_coins == 0, "Prototype wallet starts at zero")
	state.claim_reward()
	state.approve_work()
	check(not state.finish_work("planks") and state.quest_stage == state.QuestStage.AVAILABLE, "Cannot skip acceptance or approval")
	await interact_at(Vector2(384, 205))
	check(game.dialogue.detail_label.text.contains("лично тебе"), "Reward belongs to solo player")
	check(not game.dialogue.detail_label.text.contains("групп"), "Offer has no group reward")
	await capture("solo-offer.png")
	await press_primary()
	check(game.dialogue.body_label.text.contains("за тобой"), "Mira addresses one hero")
	game.dialogue.close_button.pressed.emit()
	await frames()
	await travel_at(Vector2(384, 428))
	check(not state.finish_work("goods"), "Cannot work before briefing")
	await interact_at(Vector2(526, 281))
	check(state.quest_stage == state.QuestStage.MET_CORVIN, "Corvin gives work")
	check(not game.dialogue.accept_button.visible, "Incomplete work cannot be handed in")
	await capture("corvin-work.png")
	game.dialogue.close_button.pressed.emit()
	await frames()
	check(not state.finish_work("unknown"), "Unknown task is rejected")
	await interact_at(game.WORK_POSITIONS.planks)
	check(game.busy and not game.player.controls_enabled, "Work starts and stops walking")
	var start: Vector2 = game.player.position
	Input.action_press("move_left")
	await key_press(KEY_J)
	await key_press(KEY_E)
	await frames(10)
	Input.action_release("move_left")
	check(not game.dialogue.is_open and game.player.position.distance_to(start) < 0.1, "Work blocks journal and movement")
	await capture("work-progress.png")
	await key_press(KEY_Q)
	check(not game.busy and state.completed_steps.is_empty(), "Q cancels unfinished work")
	check(game.player.controls_enabled, "Cancellation restores movement")
	await interact_at(game.WORK_POSITIONS.planks)
	await frames(100)
	check(state.completed_steps == ["planks"], "First task completes once")
	await key_press(KEY_E)
	check(not game.busy and not state.finish_work("planks"), "Completed work cannot repeat")
	await travel_at(Vector2(168, 232))
	await interact_at(Vector2(384, 205))
	check(not game.dialogue.accept_button.visible and state.personal_coins == 0, "Mira does not pay for partial work")
	game.dialogue.close_button.pressed.emit()
	await frames()
	await key_press(KEY_J)
	check(game.dialogue.detail_label.text.contains("✓ Разобрать доски"), "Journal records finished work")
	await capture("journal-work.png")
	game.dialogue.close_button.pressed.emit()
	await frames()
	await travel_at(Vector2(384, 428))
	check(game.work_spots.planks.finished, "Work marker survives leaving the square")
	for step_id in ["goods", "canopy"]:
		await interact_at(game.WORK_POSITIONS[step_id])
		await frames(100)
		check(step_id in state.completed_steps, "Work completes: " + step_id)
	check(state.quest_stage == state.QuestStage.WORK_DONE, "All three tasks require Corvin approval")
	check(state.personal_coins == 0, "Finishing work does not pay automatically")
	await capture("work-complete-square.png")
	state.claim_reward()
	check(state.personal_coins == 0, "Cannot claim before approval")
	await interact_at(Vector2(526, 281))
	check(game.dialogue.accept_button.text == "Сдать работу", "Corvin offers explicit hand-in")
	game.dialogue.close_button.pressed.emit()
	await frames()
	check(state.quest_stage == state.QuestStage.WORK_DONE, "Closing inspection does not approve")
	await key_press(KEY_E)
	await press_primary()
	check(state.quest_stage == state.QuestStage.APPROVED and state.personal_coins == 0, "Corvin signs without paying")
	await capture("corvin-approved.png")
	game.dialogue.accept_button.pressed.emit()
	check(state.quest_stage == state.QuestStage.APPROVED, "Repeated approval is harmless")
	game.dialogue.close_button.pressed.emit()
	await frames()
	await travel_at(Vector2(168, 232))
	await interact_at(Vector2(384, 205))
	check(game.dialogue.accept_button.visible and game.dialogue.accept_button.text.contains("18"), "Mira offers personal reward")
	await capture("mira-payment.png")
	await press_primary()
	check(state.quest_stage == state.QuestStage.COMPLETED and state.personal_coins == 18, "Reward pays 18 coins once")
	check(game.wallet_label.text == "Медяки: 18", "HUD wallet updates")
	await capture("mira-paid.png")
	game.dialogue.accept_button.pressed.emit()
	state.claim_reward()
	check(state.personal_coins == 18, "Repeated claim cannot duplicate coins")
	game.dialogue.close_button.pressed.emit()
	await frames()
	await key_press(KEY_E)
	check(not game.dialogue.accept_button.visible, "Reopening Mira cannot pay again")
	game.dialogue.close_button.pressed.emit()
	await frames()
	await key_press(KEY_J)
	check(game.dialogue.status_label.text == "Активных: 0 · Завершённых: 1", "Journal moves quest to completed")
	await capture("journal-completed.png")
	game.dialogue.close_button.pressed.emit()
	await frames()
	await travel_at(Vector2(384, 428))
	check(state.personal_coins == 18 and game.wallet_label.text == "Медяки: 18", "Personal wallet survives travel")
	await interact_at(Vector2(526, 281))
	check(not game.dialogue.accept_button.visible, "Corvin cannot restart completed quest")
	game.dialogue.close_button.pressed.emit()
	await frames()
	check(game.player.controls_enabled, "Control restored after completion")
	print("RESULT: %d failure(s)" % failures)
	quit(0 if failures == 0 else 1)
