extends "res://tests/save_and_pause.gd"

func interact(at: Vector2) -> void:
	game.player.position = at
	await frames()
	await key_press(KEY_E)

func click_text(parent: Node, fragment: String) -> bool:
	for child in parent.get_children():
		if child is Button and child.visible and not child.disabled and child.text.contains(fragment):
			child.pressed.emit()
			return true
	return false

func run_checks() -> void:
	state = root.get_node("GameState")
	state.save_directory = "user://quest_inventory_test_%d" % OS.get_process_id()
	clear_test_saves()
	state.reset_game()
	state.active_slot = 1
	state.game_active = true
	game = await load_world(state.GUILD_SCENE)
	await key_press(KEY_I)
	check(game.character_panel.is_open and not game.player.controls_enabled, "I opens inventory and blocks walking")
	await capture("inventory-empty.png")
	await key_press(KEY_ESCAPE)
	check(paused and game.character_panel.is_open, "Pause preserves inventory")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_I)
	check(not game.character_panel.is_open and game.player.controls_enabled, "I closes inventory")
	await interact(Vector2(384, 205))
	game.dialogue.options_button.pressed.emit()
	await frames()
	check(game.character_panel.mode == "jobs" and not game.dialogue.is_open, "Mira opens additional quest choices")
	await capture("mira-jobs.png")
	check(click_text(game.character_panel.body, "Взяться"), "Archive can be accepted through UI")
	await frames()
	check(click_text(game.character_panel.body, "Взяться"), "Parcel can be accepted alongside archive")
	check(state.side_quests.archive == "active" and state.side_quests.parcel == "active", "Two concurrent quests tracked")
	check(not state.claim_side_reward("archive"), "Unfinished work cannot pay")
	game.character_panel.close()
	await key_press(KEY_J)
	check(game.dialogue.status_label.text == "Активных: 2 · Завершённых: 0", "Journal counts concurrent quests accurately")
	await capture("journal-concurrent.png")
	game.dialogue.close()
	await interact(Vector2(650, 174))
	check(game.character_panel.mode == "work", "Guild board is reachable")
	check(click_text(game.character_panel.body, "архиве"), "Board starts archive mini-game")
	await frames(120)
	check(game.busy and game.activity_game.step == 0, "Waiting never completes work")
	await key_press(KEY_I)
	check(not game.character_panel.is_open, "Inventory cannot interrupt a mini-game")
	await key_press(KEY_3)
	check(game.activity_game.step == 0 and state.side_quests.archive == "active", "Wrong folder does not advance work")
	await capture("archive-game.png")
	await key_press(KEY_1)
	check(game.activity_game.step == 1, "Correct folder advances exactly one document")
	await key_press(KEY_ESCAPE)
	await frames(20)
	check(paused and game.activity_game.step == 1, "Pause preserves mini-game progress")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_Q)
	check(not game.busy and state.side_quests.archive == "active" and state.inventory.is_empty(), "Cancel gives no progress or item")
	await interact(Vector2(650, 174))
	click_text(game.character_panel.body, "архиве")
	await solve_activity(game)
	check(state.side_quests.archive == "ready" and state.inventory.has("sorted_records"), "Archive completion creates a quest item")
	check(state.personal_coins == 0, "Mini-game itself does not pay")
	await interact(Vector2(650, 174))
	click_text(game.character_panel.body, "Пакет")
	await solve_activity(game)
	check(state.side_quests.parcel == "packed" and state.inventory.has("permit_parcel"), "Packing creates the parcel")
	await key_press(KEY_I)
	await capture("inventory-items.png")
	check(game.character_panel.info.text.length() > 10, "Inventory has item descriptions")
	await key_press(KEY_I)
	state.attributes["Сила"] = 3
	check(state.save_game(1), "New quest state saves")
	var saved: Dictionary = state.read_slot(1)
	state.reset_game()
	check(state.apply_data(saved), "New-format save restores")
	check(state.side_quests.parcel == "packed" and state.inventory.has("permit_parcel") and state.attributes["Сила"] == 3, "Items, stages and attributes survive loading")
	var legacy: Dictionary = saved.duplicate(true)
	legacy.version = 1
	for field in ["inventory", "attributes", "side_quests", "npc_knowledge", "work_trust"]:
		legacy.erase(field)
	check(state.apply_data(legacy), "Old saves still load")
	check(state.inventory.is_empty() and state.side_quests.archive == "available", "Old save initializes new systems cleanly")
	state.apply_data(saved)
	state.pending_spawn = Vector2.INF
	await interact(Vector2(384, 428))
	await frames(8)
	game = current_scene
	await interact(Vector2(526, 281))
	check(game.dialogue.options_button.visible, "Corvin offers explicit parcel handover")
	check("permits_delivered" not in state.npc_knowledge.mira, "Mira does not learn distant delivery automatically")
	game.dialogue.options_button.pressed.emit()
	check(not state.inventory.has("permit_parcel") and state.inventory.has("delivery_receipt"), "Handover exchanges parcel for receipt")
	check(not state.deliver_parcel(), "Parcel delivery cannot repeat")
	game.dialogue.close()
	await interact(Vector2(168, 232))
	await frames(8)
	game = current_scene
	await interact(Vector2(384, 205))
	game.dialogue.options_button.pressed.emit()
	await frames()
	check(click_text(game.character_panel.body, "8 медяков"), "Mira pays archive through UI")
	await frames()
	check(click_text(game.character_panel.body, "6 медяков"), "Mira pays delivery through UI")
	check(state.personal_coins == 14 and state.inventory.is_empty(), "Both quests pay once and consume proof items")
	check(not state.claim_side_reward("archive") and not state.claim_side_reward("parcel") and state.personal_coins == 14, "Repeated claims do not duplicate rewards")
	check(state.work_trust.mira == 2 and "permits_delivered" in state.npc_knowledge.mira, "Reporting delivery changes Mira's knowledge and work trust")
	game.character_panel.close()
	await key_press(KEY_J)
	game.dialogue.options_button.pressed.emit()
	await frames()
	await capture("all-quests.png")
	check(game.character_panel.mode == "quests", "Journal lists all three quests")
	game.character_panel.close()
	state.save_game(1)
	check(state.apply_data(state.read_slot(1)) and state.work_trust.mira == 2, "NPC knowledge and trust persist")
	clear_test_saves()
	print("RESULT: %d failure(s)" % failures)
	quit(0 if failures == 0 else 1)
