extends "res://tests/quests_inventory.gd"
## Menu navigation, persisted tracking, focus isolation and viewport bounds.

func fits(control: Control, message: String) -> void:
	var rect := control.get_global_rect()
	check(Rect2(Vector2.ZERO, Vector2(640, 360)).encloses(rect), message + " " + str(rect))

func run_checks() -> void:
	state = root.get_node("GameState")
	state.save_directory = "user://ui_workflow_%d" % OS.get_process_id()
	state.reset_game()
	state.active_slot = 1
	state.game_active = true
	game = await load_world(state.GUILD_SCENE)
	check(not game.objective_label.visible and game.objective_label.text.is_empty(), "No quest leaves HUD objective empty")
	await capture("hud.png")
	game.hud.show_toast("Получено 18 медяков")
	game.hud.on_saved(1, "reward")
	await frames()
	check(game.hud.toast_panel.size.x <= 210 and game.hud.toast_panel.size.y <= 48, "Reward notice stays compact")
	fits(game.hud.toast_panel, "Notification stays inside viewport")
	await capture("notification.png")
	await key_press(KEY_I)
	await frames()
	check(not game.hud.toast_panel.visible, "Notification waits behind a modal menu")
	var remaining: float = game.hud.toast_remaining
	await frames(8)
	check(game.hud.toast_remaining == remaining, "Hidden notification does not expire unread")
	check(game.character_panel.mode == "inventory" and not game.player.controls_enabled, "I opens bag with movement blocked")
	fits(game.character_panel.panel, "Bag fits viewport")
	await capture("bag-empty.png")
	await key_press(KEY_J)
	check(game.character_panel.mode == "quests", "J switches directly from bag to quests")
	check(visible_text(game.character_panel).contains("Нет активных заданий"), "Empty journal gives a next step")
	await key_press(KEY_I)
	check(game.character_panel.mode == "inventory", "I switches directly back to bag")
	game.character_panel.switch_tab("hero")
	await frames()
	fits(game.character_panel.panel, "Hero fits viewport")
	await capture("hero.png")
	var focus_before := root.gui_get_focus_owner()
	await key_press(KEY_ESCAPE)
	check(paused and game.pause_menu.resume_button.has_focus(), "Pause takes keyboard focus")
	await key_press(KEY_TAB)
	check(game.pause_menu.home.is_ancestor_of(root.gui_get_focus_owner()), "Tab cannot reach underlying menu")
	await key_press(KEY_UP)
	check(game.pause_menu.home.is_ancestor_of(root.gui_get_focus_owner()), "Arrows cannot reach underlying menu")
	game.pause_menu.open_help()
	await frames()
	fits(game.pause_menu.root_panel, "Controls screen fits viewport")
	await capture("controls.png")
	await key_press(KEY_ESCAPE)
	check(paused and game.pause_menu.home.visible, "Escape returns from controls to pause")
	await key_press(KEY_ESCAPE)
	check(root.gui_get_focus_owner() == focus_before, "Resume restores the prior focused tab")
	game.character_panel.close()
	state.accept_quest()
	state.accept_side_quest("archive")
	state.accept_side_quest("parcel")
	state.meet_corvin()
	await frames()
	fits(game.objective_label, "Current objective fits top-right HUD")
	await capture("hud-active.png")
	await key_press(KEY_J)
	check(game.character_panel.quest_buttons.size() == 3, "All three accepted quests visible at once")
	await key_press(KEY_PAGEDOWN)
	check(game.character_panel.detail_scroll.scroll_vertical > 0, "Long quest details scroll with keyboard")
	await key_press(KEY_PAGEUP)
	check(game.character_panel.detail_scroll.scroll_vertical == 0, "PageUp returns to quest heading")
	game.character_panel.quest_buttons.parcel.pressed.emit()
	check(click_text(game.character_panel.quest_actions, "Отслеживать"), "Tracking selected through UI")
	await frames()
	check(state.current_tracked_quest() == "parcel" and game.objective_label.text == state.side_objective("parcel"), "HUD follows selected quest")
	fits(game.character_panel.panel, "Journal fits viewport")
	await capture("journal.png")
	check(state.read_slot(1).tracked_quest == "parcel", "Tracking is saved to active slot")
	var old: Dictionary = state.read_slot(1)
	old.erase("tracked_quest")
	check(state.apply_data(old) and state.current_tracked_quest() == "fair", "Old saves select an active quest automatically")
	state.track_quest("parcel")
	check(not state.track_quest("unknown"), "Unknown quest cannot be tracked")
	game.character_panel.close()
	state.finish_side_work("archive")
	state.finish_side_work("parcel")
	await key_press(KEY_I)
	await frames()
	check(game.character_panel.item_buttons.size() == 2, "Bag displays earned items")
	game.character_panel.item_buttons.permit_parcel.grab_focus()
	check(game.character_panel.info.text.contains("Корвину"), "Keyboard selection reveals item recipient")
	await capture("bag-items.png")
	game.character_panel.close()
	state.deliver_parcel()
	state.claim_side_reward("parcel")
	check(state.current_tracked_quest() != "parcel", "Completed quest automatically yields tracker to active quest")
	await key_press(KEY_J)
	game.character_panel.set_filter(true)
	await frames()
	check(game.character_panel.quest_buttons.size() == 1 and visible_text(game.character_panel).contains("Получено: 6"), "Completed filter shows actual paid reward")
	await capture("journal-complete.png")
	game.character_panel.close()
	game.player.position = Vector2(384, 205)
	await frames()
	game.hud.action_button.pressed.emit()
	check(game.dialogue.is_open, "Context button opens nearby NPC")
	await frames()
	fits(game.dialogue.panel, "Dialogue fits viewport")
	await capture("dialogue.png")
	game.dialogue.options_button.pressed.emit()
	await frames()
	check(game.dialogue.is_open and not game.character_panel.is_open, "Other work remains a conversation")
	fits(game.dialogue.panel, "Conversation topics fit viewport")
	await capture("jobs.png")
	check(click_text(game.dialogue.topic_buttons, "архив"), "Archive remains in NPC dialogue")
	await frames()
	fits(game.dialogue.panel, "Side quest dialogue fits viewport")
	await capture("dialogue-archive.png")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_ESCAPE)
	check(game.dialogue.topic == "archive", "Pause preserves conversation topic")
	game.dialogue.close()
	await key_press(KEY_ESCAPE)
	await frames()
	fits(game.pause_menu.root_panel, "Pause fits viewport")
	await capture("pause.png")
	game.pause_menu.open_save_slots()
	await frames()
	fits(game.pause_menu.root_panel, "Five slots fit viewport")
	await capture("save-slots.png")
	game.pause_menu.select_save_slot(1, true)
	check(game.pause_menu.confirm_no.has_focus(), "Overwrite defaults to Cancel")
	await key_press(KEY_TAB)
	check(game.pause_menu.confirm_overlay.is_ancestor_of(root.gui_get_focus_owner()), "Confirmation keeps focus inside itself")
	await key_press(KEY_LEFT)
	check(game.pause_menu.confirm_overlay.is_ancestor_of(root.gui_get_focus_owner()), "Arrow focus stays in confirmation")
	await key_press(KEY_ESCAPE)
	await key_press(KEY_ESCAPE)
	await key_press(KEY_ESCAPE)
	check(not paused, "Escape unwinds confirmation, slots, pause")
	state.return_to_main_menu()
	await frames()
	var menu = current_scene
	menu.open_slots("load")
	await frames()
	fits(menu.slot_panel, "Load screen fits viewport")
	await capture("load-slots.png")
	menu.request_delete(1)
	check(menu.confirm_no.has_focus(), "Delete defaults to Cancel")
	await key_press(KEY_ENTER)
	check(not state.read_slot(1).is_empty() and not menu.confirm_overlay.visible, "Default Enter cancels deletion")
	clear_test_saves()
	print("UI WORKFLOW: %d failure(s)" % failures)
	quit(0 if failures == 0 else 1)
